### ISSUE TITLE
Create an upstart script for weave

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#113]
We have a bit of a convoluted ansible task for configuring weave. This could be simplified if we just provisioned an upstart script and started up the weave service (and let the script handle the dependencies). On a different project (which was using puppet) we had this - 

```
description "Weave Docker Network Service"
start on filesystem and started docker
stop on runlevel [!2345]

script
 [ -e /etc/default/weave ] && . /etc/default/weave
 /usr/bin/docker rm -f weave || true
 <%= scope.lookupvar('weave::bin_dir') %>/weave launch <% if @cluster_peers %><%= @cluster_peers %><% end %>
end script

respawn
respawn limit 10 10
kill timeout 10
```

We should be able to achieve something similar here. See also http://docs.docker.com/articles/host_integration/

**Comment by tayzlor** [comment]
Bumping this in priority since this could make spinning up weave in the host a bit less prone to random provisioning errors

**Comment by tayzlor** [comment]
Putting a note in here around trying to use weave connect instead of launching with peers to try and avoid random timeouts communicating between machines that result in - 

```
fatal: [46.101.42.108] => One or more undefined variables: 'dict object' has no attribute 'ansible_eth0'
```

**Comment by tayzlor** [comment]
Can we also make this dependent on docker. So instead of having to do - 

```

- name: configure weave bridge for docker
  sudo: yes
  lineinfile: "dest=/etc/default/docker state=present regexp=^DOCKER_OPTS= line='DOCKER_OPTS=\"{{ weave_docker_opts }}\"'"
  notify:
    - Restart docker
    - Weave launch
```

We could just do 

```

- name: configure weave bridge for docker
  sudo: yes
  lineinfile: "dest=/etc/default/docker state=present regexp=^DOCKER_OPTS= line='DOCKER_OPTS=\"{{ weave_docker_opts }}\"'"
  notify:
    - Restart docker
```

the restart docker would trigger a stop / start of weave.

We might have to add to the init script ```stop on stopping docker```

see http://askubuntu.com/questions/446981/how-do-i-configure-my-upstart-scripts-to-take-dependencies-into-account

needs a fair bit of testing
