### ISSUE TITLE
Move the mesos master image name into variable

### ISSUE THREAD

**Issue by enxebre** [Capgemini/Apollo#502]
Right now the mesos master image is harcoded. We need to move it into a variable so we could use mesos-ui just by exporting APOLLO_mesos_master_image before depoying apollo as all ansible variables are overridable via APOLLO_ namespace.
```
- name: run mesos-master container
 when: mesos_install_mode == "master"
 docker:
   name: mesos-master
   image: "{{ mesos_master_image }}"
```
