### ISSUE TITLE
Consider cleaning ansible default variable usage to avoid repetitive variable names

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#540]
E.g. This 

```
cadvisor_enabled: true
cadvisor_version: 'latest'
cadvisor_restart_policy: 'always'
cadvisor_net: 'bridge'
cadvisor_hostname: "{{ ansible_ssh_host }}"
cadvisor_image: "google/cadvisor:{{ cadvisor_version }}"
cadvisor_consul_dir: /etc/consul.d
cadvisor_consul_service_id: "{{ ansible_hostname }}:cadvisor:8080"
cadvisor_rebuild_container: false
```

could become - 

```
cadvisor:
  enabled: true
  version: 'latest'
  restart_policy: 'always'
  net: 'bridge'
  hostname: "{{ ansible_ssh_host }}"
  image: "google/cadvisor:{{ cadvisor_version }}"
  consul_dir: /etc/consul.d
  consul_service_id: "{{ ansible_hostname }}:cadvisor:8080"
  rebuild_container: false
```

And then in the task.yml you can reference ```cadvisor.enabled```

It might make sense not to make EVERYTHING like this and keep some stuff with the _ (maybe cadvisor_enabled / cadvisor_version??), but I dont have a strong feeling either way
